CREATE SEQUENCE EMPLOYEE_SEQ
INCREMENT BY 1
START WITH 0
NOMAXVALUE
NOCYCLE
NOCACHE;
CREATE TABLE "PUBLIC"."EMPLOYEE"(
    "EMPLOYEE_ID" INTEGER DEFAULT (EMPLOYEE_SEQ.NEXTVAL) NOT NULL,
    "AGE" INTEGER,
    "COMPANY_ID" INTEGER,
    "GENDER" VARCHAR(255),
    "NAME" VARCHAR(255),
    "SALARY" INTEGER
);
ALTER TABLE "PUBLIC"."EMPLOYEE" ADD PRIMARY KEY ("EMPLOYEE_ID");
ALTER TABLE "PUBLIC"."EMPLOYEE" ADD CONSTRAINT FK_COMPANY_ID FOREIGN KEY(COMPANY_ID) REFERENCES "PUBLIC"."COMPANY"(COMPANY_ID);