CREATE TABLE COMPANY(
    "COMPANY_ID" INTEGER DEFAULT (COMPANY_SEQ.NEXTVAL) NOT NULL,
    "COMPANY_NAME" VARCHAR(255),
    "EMPLOYEES_NUMBER" INTEGER NOT NULL
);
ALTER TABLE COMPANY ADD PRIMARY KEY (COMPANY_ID);