CREATE SEQUENCE PARKING_BOY_SEQ
INCREMENT BY 1
START WITH 0
NOMAXVALUE
NOCYCLE
NOCACHE;
CREATE TABLE "PUBLIC"."PARKING_BOY"(
    "PARKING_BOY_ID" INTEGER DEFAULT (PARKING_BOY_SEQ.NEXTVAL) NOT NULL,
    "NICKNAME" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."PARKING_BOY" ADD PRIMARY KEY("PARKING_BOY_ID");